"""init_tables

Revision ID: fbf171300e02
Revises: 
Create Date: 2025-04-17 17:08:33.935239

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fbf171300e02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__package_types'))
                    )
    op.create_index(op.f('ix__package_types_id'), 'package_types', ['id'], unique=False)
    op.create_index(op.f('ix__package_types_name'), 'package_types', ['name'], unique=True)
    op.create_table('user_sessions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('session_id', sa.String(length=100), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('last_activity', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_sessions'))
                    )
    op.create_index(op.f('ix__user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix__user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_table('packages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('weight', sa.Float(), nullable=False),
                    sa.Column('price_usd', sa.Float(), nullable=False),
                    sa.Column('package_type_id', sa.Integer(), nullable=False),
                    sa.Column('user_session_id', sa.Integer(), nullable=False),
                    sa.Column('shipping_cost', sa.Float(), nullable=True),
                    sa.Column('shipping_company_id', sa.Integer(), nullable=True),
                    sa.Column('is_shipping_cost_calculated', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['package_type_id'], ['package_types.id'],
                                            name=op.f('fk__packages__package_type_id__package_types')),
                    sa.ForeignKeyConstraint(['user_session_id'], ['user_sessions.id'],
                                            name=op.f('fk__packages__user_session_id__user_sessions')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__packages'))
                    )
    op.create_index(op.f('ix__packages_id'), 'packages', ['id'], unique=False)
    op.create_index(op.f('ix__packages_name'), 'packages', ['name'], unique=False)
    package_types = [
        dict(
            name="Одежда",
            description="Одежда и текстильные изделия"
        ),
        dict(
            name="Электроника",
            description="Электронные устройства и аксессуары"
        ),
        dict(
            name="Разное",
            description="Прочие типы посылок"
        ),
    ]
    for pt in package_types:
        op.execute(
            f"INSERT INTO package_types (name, description) VALUES ('{pt.get('name')}', '{pt.get('description')}')"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__packages_name'), table_name='packages')
    op.drop_index(op.f('ix__packages_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix__user_sessions_session_id'), table_name='user_sessions')
    op.drop_index(op.f('ix__user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix__package_types_name'), table_name='package_types')
    op.drop_index(op.f('ix__package_types_id'), table_name='package_types')
    op.drop_table('package_types')
    # ### end Alembic commands ###
